### ISSUE TITLE
Last quick issues

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Co2-Savings#29]
Emission Source type: Custom at bottom

Within biofuels list
Bagasse --> Bagasse Pulping Liquor
Landfill --> Landfill Gas

Mobile: 
Tranporation --> Freight

Remove "Other" from electricity list

Mobile emissions is broken (this could be something that is being looked at now...)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/162f5f55-3e60-46dd-be1e-9235d4dbcf79)

Graph
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/866c65de-12d2-458b-b0a2-a661799a61c7)

**Comment by koay9f** [comment]
Units in final emission output rate:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/1e89ef65-8bcb-4ec5-9d5e-b5de63098ac4)


CO2e = {energy use} x (CO2 + CH4 x 25/1000 + N2O x 298/1000)
         =   1000 GJ x (0 + 1000 x25 / 1000 + 0x298/1000)kg/GJ = 25000 kg = 25 tonne
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/0c36869c-0422-4deb-8edd-e376025fb556)



Also, the first data entry field (CO2 emissions or Global Warming Potential) doesn't seem to be hooked up
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/cc3243ce-40c2-45f0-ab3e-571c7ce7ce8d)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/601a91af-06d4-4d46-8384-1c3cc115d768)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/9df8f26c-cf18-4d5c-a37e-58465adf86b2)

**Comment by rmroot** [comment]
I think your units are messed up on what you are trying to test here. MMBTu and kg

I think you are saying the result needs to be `kg CO2e` which I just changed. Not positive the math is correct

**Comment by koay9f** [comment]
making the result kg CO2e also works.  
It was that or doing a unit conversion from kg to tonne.
